" Vim configuration by Giako
" Inspired from https://dougblack.io/words/a-good-vimrc.html

" Automate vim-plug installation
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Vim-plug support
call plug#begin('~/.vim/plugged')

Plug 'sjl/badwolf'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-endwise'
Plug 'jiangmiao/auto-pairs'
Plug 'wakatime/vim-wakatime'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-sensible'
Plug 'godlygeek/tabular'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-fugitive'
Plug 'codota/tabnine-vim'

call plug#end()

" Colors
syntax enable " enable syntax processing
colorscheme badwolf " set colorscheme
set termguicolors

" Spaces and tabs
set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number of spaces in tab when editing
set expandtab " tabs are spaces
set shiftwidth=4
filetype indent on
filetype plugin on
set autoindent

" UI config
set number " show line numbers
set wildmenu " visual autocomplete for command menu

" Key mappings
imap jk <Esc>
